// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetPreviewURL():Promise<string>;

export function GetVersion():Promise<string>;

export function LoadSite():Promise<Record<string, any>>;

export function OpenFolderDialog():Promise<Array<string>>;

export function OpenImageDialog():Promise<string>;

export function ShowPreferences():Promise<void>;

export function ShowToast(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
