// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPreviewURL() {
  return window['go']['app']['App']['GetPreviewURL']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function LoadSite() {
  return window['go']['app']['App']['LoadSite']();
}

export function OpenFolderDialog() {
  return window['go']['app']['App']['OpenFolderDialog']();
}

export function OpenImageDialog() {
  return window['go']['app']['App']['OpenImageDialog']();
}

export function ShowPreferences() {
  return window['go']['app']['App']['ShowPreferences']();
}

export function ShowToast(arg1, arg2) {
  return window['go']['app']['App']['ShowToast'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
